import {
  DropZoneArea,
  DropZoneDescription,
  DropZoneFileFormatIcon,
  DropZoneFileInfo,
  DropZoneFileItem,
  DropZoneFileList,
  DropZoneFileMeta,
  DropZoneFileName,
  DropZoneFileProgress,
  DropZoneFileProgressFill,
  DropZoneFileProgressTrack,
  DropZoneFileRemoveTrigger,
  DropZoneFileRetryTrigger,
  DropZoneIcon,
  DropZoneInput,
  DropZoneLabel,
  DropZoneRoot,
  DropZoneTrigger,
} from './drop-zone';

export { dropZoneVariants } from './drop-zone.styles';
export { useDropZonePickerContext } from './use-drop-zone-picker';

export const DropZone = Object.assign(DropZoneRoot, {
  Area: DropZoneArea,
  Description: DropZoneDescription,
  FileFormatIcon: DropZoneFileFormatIcon,
  FileInfo: DropZoneFileInfo,
  FileItem: DropZoneFileItem,
  FileList: DropZoneFileList,
  FileMeta: DropZoneFileMeta,
  FileName: DropZoneFileName,
  FileProgress: DropZoneFileProgress,
  FileProgressFill: DropZoneFileProgressFill,
  FileProgressTrack: DropZoneFileProgressTrack,
  FileRemoveTrigger: DropZoneFileRemoveTrigger,
  FileRetryTrigger: DropZoneFileRetryTrigger,
  Icon: DropZoneIcon,
  Input: DropZoneInput,
  Label: DropZoneLabel,
  Root: DropZoneRoot,
  Trigger: DropZoneTrigger,
});

export {
  DropZoneArea,
  DropZoneDescription,
  DropZoneFileFormatIcon,
  DropZoneFileInfo,
  DropZoneFileItem,
  DropZoneFileList,
  DropZoneFileMeta,
  DropZoneFileName,
  DropZoneFileProgress,
  DropZoneFileProgressFill,
  DropZoneFileProgressTrack,
  DropZoneFileRemoveTrigger,
  DropZoneFileRetryTrigger,
  DropZoneIcon,
  DropZoneInput,
  DropZoneLabel,
  DropZoneRoot,
  DropZoneTrigger,
};

export type {
  DropZoneAreaProps,
  DropZoneDescriptionProps,
  DropZoneFileFormatIconProps,
  DropZoneFileInfoProps,
  DropZoneFileItemProps,
  DropZoneFileListProps,
  DropZoneFileMetaProps,
  DropZoneFileNameProps,
  DropZoneFileProgressFillProps,
  DropZoneFileProgressProps,
  DropZoneFileProgressTrackProps,
  DropZoneFileRemoveTriggerProps,
  DropZoneFileRetryTriggerProps,
  DropZoneIconProps,
  DropZoneInputProps,
  DropZoneLabelProps,
  DropZoneRootProps as DropZoneProps,
  DropZoneRootProps,
  DropZoneTriggerProps,
} from './drop-zone';
export type { DropZoneVariants } from './drop-zone.styles';
export { dropZoneVariants as default } from './drop-zone.styles';
